flysystem:
    storages:
        event_logos_storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads/event-logos'
        brand_logos_storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads/brand-logos'
        photo_originals_storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads/photos/originals'
        photo_thumbs_storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads/photos/thumbs'
            directory_visibility: public
        photo_previews_storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/uploads/photos/previews'
            directory_visibility: public
