framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 5
                    max_delay: 0
            failed: 'doctrine://default?queue_name=failed'
        routing:
            'App\Message\ProcessPhoto': async
            'App\Message\ExtractPhotoAttributes': async
            'App\Message\SendEventLiveNotifications': async
            'App\Message\SendEventLiveEmail': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
