vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        event_logo:
            uri_prefix: ''
            upload_destination: event_logos_storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
