<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617201407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '#78 — adds user_mail_configs (per-organizer SMTP DSN, encrypted at rest) '
            . 'and user_mail_config_audits (change history).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_mail_config_audits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, actor_email_snapshot VARCHAR(254) NOT NULL, action VARCHAR(32) NOT NULL, from_addr_snapshot VARCHAR(254) NOT NULL, user_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F242965910DAF24A ON user_mail_config_audits (actor_id)');
        $this->addSql('CREATE INDEX idx_mail_audit_user ON user_mail_config_audits (user_id)');
        $this->addSql('CREATE TABLE user_mail_configs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dsn_ciphertext TEXT NOT NULL, dsn_nonce TEXT NOT NULL, from_addr VARCHAR(254) NOT NULL, verified_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, verification_token VARCHAR(64) DEFAULT NULL, verification_sent_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, from_name VARCHAR(120) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1818855EA76ED395 ON user_mail_configs (user_id)');
        $this->addSql('ALTER TABLE user_mail_config_audits ADD CONSTRAINT FK_F2429659A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_mail_config_audits ADD CONSTRAINT FK_F242965910DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_mail_configs ADD CONSTRAINT FK_1818855EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_mail_config_audits DROP CONSTRAINT FK_F2429659A76ED395');
        $this->addSql('ALTER TABLE user_mail_config_audits DROP CONSTRAINT FK_F242965910DAF24A');
        $this->addSql('ALTER TABLE user_mail_configs DROP CONSTRAINT FK_1818855EA76ED395');
        $this->addSql('DROP TABLE user_mail_config_audits');
        $this->addSql('DROP TABLE user_mail_configs');
    }
}
