<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625104354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create audit_log table for admin action audit trail (#75)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(64) NOT NULL, actor_id INT DEFAULT NULL, actor_label VARCHAR(180) DEFAULT NULL, target_type VARCHAR(64) DEFAULT NULL, target_id INT DEFAULT NULL, target_label VARCHAR(255) DEFAULT NULL, context JSON NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_created_at ON audit_log (created_at)');
        $this->addSql('CREATE INDEX idx_audit_target ON audit_log (target_type, target_id)');
        $this->addSql('CREATE INDEX idx_audit_actor ON audit_log (actor_id)');
        $this->addSql('CREATE INDEX idx_audit_action ON audit_log (action)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE audit_log');
    }
}
