<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260621125937 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '#77 visitor email notification subscriptions + event publish state';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_notification_subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, confirmation_token VARCHAR(64) DEFAULT NULL, unsubscribe_token VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmation_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, unsubscribed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAC08E3E71F7E88B ON event_notification_subscriptions (event_id)');
        $this->addSql('CREATE INDEX idx_event_notif_event_status ON event_notification_subscriptions (event_id, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_notif_event_email ON event_notification_subscriptions (event_id, email)');
        $this->addSql('ALTER TABLE event_notification_subscriptions ADD CONSTRAINT FK_EAC08E3E71F7E88B FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE events ADD notifications_enabled BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_notification_subscriptions DROP CONSTRAINT FK_EAC08E3E71F7E88B');
        $this->addSql('DROP TABLE event_notification_subscriptions');
        $this->addSql('ALTER TABLE events DROP published_at');
        $this->addSql('ALTER TABLE events DROP notifications_enabled');
    }
}
