<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260715201538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '#109 bib suppress-list table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bib_suppressions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, bib_number VARCHAR(64) NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CCFCB1E171F7E88B ON bib_suppressions (event_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_bib_suppression_event_bib ON bib_suppressions (event_id, bib_number)');
        $this->addSql('ALTER TABLE bib_suppressions ADD CONSTRAINT FK_CCFCB1E171F7E88B FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD bib_indexing_enabled BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bib_suppressions DROP CONSTRAINT FK_CCFCB1E171F7E88B');
        $this->addSql('DROP TABLE bib_suppressions');
        $this->addSql('ALTER TABLE events DROP bib_indexing_enabled');
    }
}
