<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260716195722 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '#109: photo_attributes table for extracted searchable tags';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE photo_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, value VARCHAR(64) NOT NULL, confidence DOUBLE PRECISION DEFAULT NULL, photo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7DFF70787E9E4C8C ON photo_attributes (photo_id)');
        $this->addSql('CREATE INDEX idx_photo_attributes_photo_type ON photo_attributes (photo_id, type)');
        $this->addSql('CREATE INDEX idx_photo_attributes_type_value ON photo_attributes (type, value)');
        $this->addSql('ALTER TABLE photo_attributes ADD CONSTRAINT FK_7DFF70787E9E4C8C FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE photo_attributes DROP CONSTRAINT FK_7DFF70787E9E4C8C');
        $this->addSql('DROP TABLE photo_attributes');
    }
}
