<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612165909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_identities table for federated identities (#19).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_identities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, provider VARCHAR(32) NOT NULL, subject VARCHAR(191) NOT NULL, email VARCHAR(180) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D5EEA04A76ED395 ON user_identities (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_identity_provider_subject ON user_identities (provider, subject)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_identity_user_provider ON user_identities (user_id, provider)');
        $this->addSql('ALTER TABLE user_identities ADD CONSTRAINT FK_5D5EEA04A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_identities DROP CONSTRAINT FK_5D5EEA04A76ED395');
        $this->addSql('DROP TABLE user_identities');
    }
}
