<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610124901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add photos table with unique (event_id, content_hash) and index on (event_id, status, taken_at)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE photos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(16) NOT NULL, processing_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content_hash VARCHAR(64) NOT NULL, original_filename VARCHAR(255) NOT NULL, byte_size INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_876E0D971F7E88B ON photos (event_id)');
        $this->addSql('CREATE INDEX idx_photos_event_status_taken_at ON photos (event_id, status, taken_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_photos_event_hash ON photos (event_id, content_hash)');
        $this->addSql('ALTER TABLE photos ADD CONSTRAINT FK_876E0D971F7E88B FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE photos DROP CONSTRAINT FK_876E0D971F7E88B');
        $this->addSql('DROP TABLE photos');
    }
}
