<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609172304 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_collections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(120) NOT NULL, name VARCHAR(200) NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78AC006E7E3C61F9 ON event_collections (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_collections_slug ON event_collections (slug)');
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, default_window_minutes INT DEFAULT NULL, slug VARCHAR(120) NOT NULL, name VARCHAR(200) NOT NULL, date DATE NOT NULL, collection_id INT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5387574A514956FD ON events (collection_id)');
        $this->addSql('CREATE INDEX IDX_5387574A7E3C61F9 ON events (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_events_slug ON events (slug)');
        $this->addSql('ALTER TABLE event_collections ADD CONSTRAINT FK_78AC006E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A514956FD FOREIGN KEY (collection_id) REFERENCES event_collections (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_collections DROP CONSTRAINT FK_78AC006E7E3C61F9');
        $this->addSql('ALTER TABLE events DROP CONSTRAINT FK_5387574A514956FD');
        $this->addSql('ALTER TABLE events DROP CONSTRAINT FK_5387574A7E3C61F9');
        $this->addSql('DROP TABLE event_collections');
        $this->addSql('DROP TABLE events');
    }
}
