<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611135938 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add invitations table for single-use signup links (#31).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE invitations (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              selector VARCHAR(32) NOT NULL,
              hashed_verifier VARCHAR(64) NOT NULL,
              role VARCHAR(32) NOT NULL,
              email VARCHAR(180) DEFAULT NULL,
              created_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                expires_at TIMESTAMP(0)
              WITH
                TIME ZONE NOT NULL,
                used_at TIMESTAMP(0)
              WITH
                TIME ZONE DEFAULT NULL,
                revoked_at TIMESTAMP(0)
              WITH
                TIME ZONE DEFAULT NULL,
                created_by_id INT NOT NULL,
                used_by_id INT DEFAULT NULL,
                revoked_by_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_232710AEB03A8386 ON invitations (created_by_id)');
        $this->addSql('CREATE INDEX IDX_232710AE4C2B72A8 ON invitations (used_by_id)');
        $this->addSql('CREATE INDEX IDX_232710AEFB8FE773 ON invitations (revoked_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_invitations_selector ON invitations (selector)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              invitations
            ADD
              CONSTRAINT FK_232710AEB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              invitations
            ADD
              CONSTRAINT FK_232710AE4C2B72A8 FOREIGN KEY (used_by_id) REFERENCES users (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              invitations
            ADD
              CONSTRAINT FK_232710AEFB8FE773 FOREIGN KEY (revoked_by_id) REFERENCES users (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invitations DROP CONSTRAINT FK_232710AEB03A8386');
        $this->addSql('ALTER TABLE invitations DROP CONSTRAINT FK_232710AE4C2B72A8');
        $this->addSql('ALTER TABLE invitations DROP CONSTRAINT FK_232710AEFB8FE773');
        $this->addSql('DROP TABLE invitations');
    }
}
