<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701194240 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add organizer color styling (StyleSettings) to events, collections, and organizer_profiles (#54)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE organizer_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, style_font_color VARCHAR(7) DEFAULT NULL, style_background_color VARCHAR(7) DEFAULT NULL, style_button_color VARCHAR(7) DEFAULT NULL, style_glow_enabled BOOLEAN DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_organizer_profiles_user ON organizer_profiles (user_id)');
        $this->addSql('ALTER TABLE organizer_profiles ADD CONSTRAINT FK_69C1CE93A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_collections ADD style_font_color VARCHAR(7) DEFAULT NULL');
        $this->addSql('ALTER TABLE event_collections ADD style_background_color VARCHAR(7) DEFAULT NULL');
        $this->addSql('ALTER TABLE event_collections ADD style_button_color VARCHAR(7) DEFAULT NULL');
        $this->addSql('ALTER TABLE event_collections ADD style_glow_enabled BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE events ADD style_font_color VARCHAR(7) DEFAULT NULL');
        $this->addSql('ALTER TABLE events ADD style_background_color VARCHAR(7) DEFAULT NULL');
        $this->addSql('ALTER TABLE events ADD style_button_color VARCHAR(7) DEFAULT NULL');
        $this->addSql('ALTER TABLE events ADD style_glow_enabled BOOLEAN DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE organizer_profiles DROP CONSTRAINT FK_69C1CE93A76ED395');
        $this->addSql('DROP TABLE organizer_profiles');
        $this->addSql('ALTER TABLE event_collections DROP style_font_color');
        $this->addSql('ALTER TABLE event_collections DROP style_background_color');
        $this->addSql('ALTER TABLE event_collections DROP style_button_color');
        $this->addSql('ALTER TABLE event_collections DROP style_glow_enabled');
        $this->addSql('ALTER TABLE events DROP style_font_color');
        $this->addSql('ALTER TABLE events DROP style_background_color');
        $this->addSql('ALTER TABLE events DROP style_button_color');
        $this->addSql('ALTER TABLE events DROP style_glow_enabled');
    }
}
